<?php
include_once realpath(dirname(__FILE__)) . "/../includes.php";
writeHeader("Register");
?>
<body style="background-image: url(./assets/img/water.jpg); background-size: cover">
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 col-sm-10 col-12">
            <img src="./assets/img/logo.png" alt="" class="img-responsive w-25 mb-4">
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-sm-6 col-12 mx-auto ">
            <div class="login-box shadow">
                <h4 class="text-center font-weight-bold"><strong>REGISTER</strong></h4>
                <?php if (isset($message) && trim($message) != "") { ?>
                    <div class="row">
                        <div class="col-12">
                            <p class="alert alert-danger text-center"><small><?php echo $message; ?></small></p>
                        </div>
                    </div>
                <?php } ?>
                <form id="register" method="post" action="register">
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <label for="firstname">FIRST NAME:</label>
                                <input type="text" id="firstname" name="firstname" maxlength="80"
                                       class="form-control input-box rounded-0" required
                                       value="<?php echo($firstname ?? ""); ?>">
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="lastname">LAST NAME:</label>
                                <input type="text" id="lastname" name="lastname" maxlength="80" required
                                       value="<?php echo($lastname ?? ""); ?>"
                                       class="form-control input-box rounded-0">
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <label for="email">EMAIL:</label>
                                <input type="email" id="email" name="email" maxlength="255" required
                                       value="<?php echo($email ?? ""); ?>"
                                       class="form-control input-box rounded-0">
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <label for="password">PASSWORD:</label>
                                <input type="password" id="password" name="password" maxlength="80" required
                                       class="form-control input-box rounded-0">
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <label for="confirm-password">CONFIRM PASSWORD:</label>
                                <input type="password" id="confirm-password" name="confirm-password" maxlength="80" required
                                       class="form-control input-box rounded-0">
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="row">
                                <div class="col-8">
                                    <small class="font-weight-bold">
                                        Already have an account?<br>
                                        Click here to <a href="login" class="orange-link">Login</a>
                                    </small>
                                </div>
                                <div class="col-4 text-right">
                                    <button type="submit" class="btn btn-dark-blue btn-lg font-weight-bold rounded-0">
                                        REGISTER
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</body>
</html>