<?php
include_once realpath(dirname(__FILE__)) . "/../includes.php";
writeHeader("Forgot Your Password");
?>
    <body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 col-sm-10 col-12">
            <img src="./assets/img/logo.png" alt="" class="img-responsive w-25 mb-4">
        </div>
    </div>
    <div class="row">
    <div class="col-md-4 col-sm-6 col-12 mx-auto ">
    <div class="login-box shadow">
    <h4 class="text-center font-weight-bold"><strong>FORGOT YOUR PASSWORD?</strong></h4>
    <p>If you forgot your password, please enter your email address so we can send you a link to reset your password.</p>
        <?php if (isset($message) && trim($message) != "") { ?>
            <div class="row">
                <div class="col-12">
                    <p class="alert alert-danger text-center"><small><?php echo $message; ?></small></p>
                </div>
            </div>
        <?php } ?>
    <form id="register" method="post" action="forgot_password">
        <div class="row">
            <div class="col-12">
                <div class="form-group">
                    <label for="email">Email</label>
                    <input id="email" name="email" required type="email"
                           class="form-control input-box rounded-0"
                           value="<?php echo($email ?? ""); ?>"
                           maxlength="255">
                </div>
            </div>
            <div class="col-12">
                <div class="row">
                    <div class="col-8">
                        <small class="font-weight-bold">
                            Remember you password? Click to <a href="login" class="orange-link">login</a></small>
                    </div>
                    <div class="col-4 text-right">
                        <button type="submit" class="btn btn-dark-blue btn-lg font-weight-bold rounded-0">SUBMIT</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
