<?php
include_once realpath(dirname(__FILE__)) . "/../includes.php";
writeHeader("Login");
?>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 col-sm-10 col-12">
            <img src="./assets/img/logo.png" alt="" class="img-responsive w-25 mb-4">
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-sm-6 col-12 mx-auto ">
            <div class="login-box shadow">
                <h4 class="text-center font-weight-bold"><strong>PLEASE LOGIN</strong></h4>
                <?php if (isset($message) && trim($message) != "") { ?>
                    <div class="row">
                        <div class="col-12">
                            <p class="alert alert-danger text-center"><small><?php echo $message; ?></small></p>
                        </div>
                    </div>
               <?php } ?>
                <form id="login" method="post" action="login">
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <label for="username">USERNAME:</label>
                                <input id="username" name="username"
                                       class="form-control input-box rounded-0" maxlength="255"
                                       value="<?php echo($username ?? ""); ?>">
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <label for="password">PASSWORD:</label>
                                <input type="password" id="password" name="password"
                                       class="form-control input-box rounded-0"
                                       maxlength="80" value="<?php echo($password ?? ""); ?>">
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="row">
                                <div class="col-8">
                                    <small class="font-weight-bold">
                                        Forgot your <a href="forgot_password" class="orange-link">password</a>?<br/>
                                        Need to <a href="register" class="orange-link">register</a> a new account?
                                    </small>
                                </div>
                                <div class="col-4 text-right">
                                    <button type="submit" class="btn btn-dark-blue btn-lg font-weight-bold rounded-0">LOGIN</button>
                                </div>
                            </div>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
</body>
</html>