<?php
include_once realpath(dirname(__FILE__)) . "/../includes.php";
writeHeader("Password Reset Link Emailed");
?>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 col-sm-10 col-12">
            <img src="./assets/img/logo.png" alt="" class="img-responsive w-25 mb-4">
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-sm-6 col-12 mx-auto ">
            <div class="login-box shadow">
                <h4 class="text-center font-weight-bold"><strong>PASSWORD RESET LINK SENT!</strong></h4>
                <p>Please check your email (<?php echo $email; ?>) for a link to reset your password.</p>
                <div class="row">
                    <div class="col-12">
                        <div class="row">
                            <div class="col-8">
                                <small class="font-weight-bold">
                                    Remember you password? Click to
                                    <a href="login" class="orange-link">login</a></small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>